config/routes.rb
Rails.application.routes.draw do
  resources :types
  resources :markers
  resources :categories


  get 'marker_category/' , to: 'categories#marker_category'


  root 'markers#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/marker.rb
class Marker < ApplicationRecord
    belongs_to :category
    belongs_to :type




end

app/controllers/markers_controller.rb
class MarkersController < ApplicationController
  before_action :set_marker, only: %i[ show edit update destroy ]

  # GET /markers or /markers.json
  def index
    @marker = Marker.new
    if params[:search]
      @markers = Marker.where("name LIKE ? OR url LIKE ?", "%#{params[:search]}%" , "%#{params[:search]}%") 
      respond_to do |format|
        format.html {redirect_to root_path}
      format.json {render json: @markers}
      format.js 
      end
    else
      @markers = Marker.all
    end
  end

  # GET /markers/1 or /markers/1.json
  def show
  end

  # GET /markers/new
  def new
    @marker = Marker.new
  end

  # GET /markers/1/edit
  def edit
    @types = Type.all
    @categories = Category.all
  end

  # POST /markers or /markers.json
  def create
    @marker = Marker.new(marker_params)

    respond_to do |format|
      if @marker.save
        format.html { redirect_to @marker, notice: "Marker was successfully created." }
        format.json { render :show, status: :created, location: @marker }
        format.js 
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @marker.errors, status: :unprocessable_entity }
        format.js { render :new }
      end
    end
    @types = Type.all
  end

  # PATCH/PUT /markers/1 or /markers/1.json
  def update
    respond_to do |format|
      if @marker.update(marker_params)
        format.html { redirect_to @marker, notice: "Marker was successfully updated." }
        format.json { render :show, status: :ok, location: @marker }
        format.js 
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @marker.errors, status: :unprocessable_entity }
        format.js { render :edit }
      end
    end
    @types = Type.all
  end

  # DELETE /markers/1 or /markers/1.json
  def destroy
    @marker.destroy
    respond_to do |format|
      format.html { redirect_to markers_url, notice: "Marker was successfully destroyed." }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marker
      @marker = Marker.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def marker_params
      params.require(:marker).permit(:url, :name, :type_id, :category_id)
    end

    def category_params
      params.require(:category)
    end
end

app/helpers/markers_helper.rb
module MarkersHelper
end

app/views/markers/_form.html.erb
<%= form_with(model: marker, remote: true) do |form| %>
  <% if marker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(marker.errors.count, "error") %> prohibited this marker from being saved:</h2>
      <ul>
        <% marker.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%# nostros %>
  <div class="field mb-2">
    <%= form.label :name, 'Nombre del marcador' %>
    <%= form.text_field :name %>
  </div>
  <div class="field mb-2">
    <%= form.label :url, "Ingrese URL" %>
    <%= form.url_field :url  %>
  </div>
  <div class="field mb-2">
    <%= form.label :type_id, 'Tipo' %>
    <%= form.select :type_id, Type.all.collect {|t| [t.name, t.id]}, {} ,id: :marker_type_id  %>
  </div>
  <div class="field mb-2">
    <%= form.label :category_id, 'Categoria' %>
    <%= form.select :category_id, Category.all.collect {|c| [c.name, c.id]}, {} ,id: :marker_category_id  %>
  </div>
  <div class="actions">
    <%= form.submit class:'btn btn-primary', data: { confirm: '¿estas seguro?' }  %>
  </div>
<% end %>

app/views/markers/_marker.html.erb
<tr id="marker_<%= marker.id %>">
  <td><%= marker.name %></td>
  <td><%= marker.type.name %></td>
  <td><%= marker.category.name %></td>
  <td><%= marker.url %></td>
  <td><%= link_to 'Show', marker, class: "btn btn-primary", remote: true %></td>
  <td><%= link_to 'Edit', edit_marker_path(marker), class:"btn btn-success", remote: true %></td>
  <td><%= link_to marker, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger", remote: true do %>
      <i class="fas fa-trash-alt"></i>
    <% end %></td>
</tr>

app/views/markers/_modal_marker.html.erb
<div class="modal fade" id="modalMarkers" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-markers-title"> <strong>Marker</strong></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id="modal-body-markers">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/markers/_show.html.erb
<h6><strong>Marker: </strong><%= @marker.name %></h6>
<h6><strong>Nombre Tipo: </strong><%= @marker.type.name %></h6>
<h6><strong>Nombre de Categoria: </strong><%= @marker.category.name %></h6>
<h6><strong>Url: </strong><%= @marker.url %></h6>

app/views/markers/create.js.erb
document.querySelector('tbody').insertAdjacentHTML('beforeend', '<%= j render @marker %>') 

app/views/markers/destroy.js.erb
$('#marker_<%= @marker.id %>').fadeOut();

app/views/markers/edit.html.erb
<h1>Editing Marker</h1>

<%= render 'form', marker: @marker %>

<%= link_to 'Show', @marker %> |
<%= link_to 'Back', markers_path %>

app/views/markers/edit.js.erb
$('#modal-markers-title').html("Editar Marker");
$('#modal-body-markers').html('<%= j render "form", marker: @marker %>');
$('#modalMarkers').modal("show");

app/views/markers/index.html.erb
<div id="resultados">
</div>
<%= form_tag "/search/create", method: :get, remote: true, id: "search-form" do %>
  <%= text_field_tag :keyword, nil, placeholder: "Qué estás buscando"  %>
  <%= content_tag :button, type: :submit do %>
    Buscar
  <% end %>
<% end %>
<div class="card col-xs">
  <div class="card-header d-flex justify-content-start">
    <div class="m-0">
      <%= link_to new_marker_path, {remote: true, class: "btn btn-success text-left", id: "anadir-marker-btn"}  do %>
        <span class="fas fa-plus-square" ></span>
      <% end %>
    </div>
    <h1 class="h3 mx-5 text-gray-800 text-center">Markers</h1>
  </div>
</div>
<div class="card m-2 " >
  <table class="table border-primary">
    <thead>
      <tr>
        <th class="text-center">Name</th>
        <th class="text-center">Type</th>
        <th class="text-center">Category</th>
        <th class="text-center">Url</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @markers.each do |marker| %>
        <%= render 'markers/marker', marker: marker %>
      <% end %>
    </tbody>
  </table>
</div>
<%= render 'modal_marker' %>

app/views/markers/new.html.erb
<h1>New Marker</h1>

<%= render 'form', marker: @marker %>

<%= link_to 'Back', markers_path %>

app/views/markers/new.js.erb
// Add the dialog title
$('#modal-markers-title').html("Nuevo Marker");
// Render the new form
$('#modal-body-markers').html('<%= j render 'markers/form', marker: @marker %>');
// Show the dynamic dialog
$('#modalMarkers').modal("show");

app/views/markers/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @marker.name %>
</p>
<p>
  <strong>Url:</strong>
  <%= @marker.url %>
</p>
<p>
  <strong>Type:</strong>
  <%= @marker.type.name %>
</p>
<p>
  <strong>Category:</strong>
  <%= @marker.category.name %>
</p>
<%= link_to 'Edit', edit_marker_path(@marker) %> |
<%= link_to 'Back', markers_path %>

app/views/markers/show.js.erb
$('#modal-body-markers').html('<%= j render "show" %>');
$('#modalMarkers').modal("show");

app/views/markers/update.js.erb
document.querySelector('#marker_<%= @marker.id %>').innerHTML = "<%= j render @marker%>"
document.querySelector('#edit').innerHTML = " "