config/routes.rb
Rails.application.routes.draw do
  resources :types
  resources :markers
  resources :categories


  get 'marker_category/' , to: 'categories#marker_category'


  root 'markers#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: %i[ show edit update destroy ]

  # GET /types or /types.json
  def index
    @types = Type.all
    @types_graf = Type.type_grafico

  end

  # GET /types/1 or /types/1.json
  def show
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types or /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: "Type was successfully created." }
        format.json { render :show, status: :created, location: @type }
        format.js
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @type.errors, status: :unprocessable_entity }
        format.js { render :new}

      end
    end
  end

  # PATCH/PUT /types/1 or /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to @type, notice: "Type was successfully updated." }
        format.json { render :show, status: :ok, location: @type }
        format.js

      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @type.errors, status: :unprocessable_entity }
        format.js {render :edit}

      end
    end
  end

  # DELETE /types/1 or /types/1.json
  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url, notice: "Type was successfully destroyed." }
      format.json { head :no_content }
      format.js

    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def type_params
      params.require(:type).permit(:name)
    end
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/types/_form.html.erb
<%= form_with(model: type, remote: true) do |form| %>
  <% if type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(type.errors.count, "error") %> prohibited this type from being saved:</h2>
      <ul>
        <% type.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field mb-2">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="actions">
    <%= form.submit class: "btn btn-secondary"%>
  </div>
<% end %>

app/views/types/_modal_types.html.erb
<!-- Modal -->
<div class="modal fade" id="modalTypes" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-types-title"> <strong>Type</strong></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id="modal-body-types">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/types/_show.html.erb
<h6><strong>Type: </strong><%= @type.name %></h6>

app/views/types/_type.html.erb
<tr id="type_<%= type.id %>">
  <td><%= type.name %></td>
  <td><%= link_to 'Show', type, class:"btn btn-primary", remote: true %></td>
  <td><%= link_to 'Edit', edit_type_path(type), class:"btn btn-success", remote: true %></td>
  <td><%= link_to type, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger", remote: true do %>
      <i class="fas fa-trash-alt"></i>
    <% end %></td>
</td>
</tr>

app/views/types/destroy.js.erb
$('#type_<%= @type.id %>').fadeOut();

app/views/types/edit.html.erb
<h1>Editing Type</h1>

<%= render 'form', type: @type %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

app/views/types/edit.js.erb
$('#modal-types-title').html("Editar Type");
$('#modal-body-types').html('<%= j render "form", type: @type %>');
$('#modalTypes').modal("show");

app/views/types/index.html.erb
<p id="notice"><%= notice %></p>
<%= pie_chart @types_graf %>
<div class="card">
  <div class="card-header d-flex justify-content-start">
    <div class="m-0">
      <%= link_to new_type_path, {remote: true, class: "btn btn-success text-left", id: "anadir-marker-btn"}  do %>
        <span class="fas fa-plus-square" ></span>
      <% end %>
    </div>
    <h1 class="h3 mx-5 text-gray-800 text-center">Type</h1>
  </div>
</div>
<div class="card m-2">
  <table class="table border-primary">
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @types.each do |type| %>
        <%= render 'types/type', type: type %>
      <% end %>
    </tbody>
  </table>
</div>
<%= render 'modal_types' %>

app/views/types/new.html.erb
<h1>New Type</h1>

<%= render 'form', type: @type %>

<%= link_to 'Back', types_path %>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @type.name %>
</p>

<%= link_to 'Edit', edit_type_path(@type) %> |
<%= link_to 'Back', types_path %>

app/views/types/show.js.erb
$('#modal-body-types').html('<%= j render "show" %>');
$('#modalTypes').modal("show");

app/views/types/update.js.erb
document.querySelector('#type_<%= @type.id %>').innerHTML = "<%= j render @type%>"
document.querySelector('#edit').innerHTML = " "